---
# tasks file for roles/ubuntu/elk
- name: Install Prerequisites
  apt:
    name:
      - openjdk-11-jdk
      - nginx
    state: latest
    update_cache: yes

- name: Add Elasticsearch Repository
  apt_key:
    url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Get APT transport https
  apt:
    name: apt-transport-https
    state: present

- name: Repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Elasticsearch network
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.host: localhost'

- name: Elasticsearch port
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'http.port'
    line: 'http.port: 9200'

- name: Discovery Type
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    line: 'discovery.type: singel-node'

- name: Reload
  systemd:
    daemon_reload: yes

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started

- name: Install Kibana
  apt:
    name: kibana
    update_cache: yes

- name: Server host
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.host:'
    line: 'server.host: localhost'

- name: Server Port
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.port:'
    line: 'server.port: 5601'

- name: Start Kibana
  service:
    name: kibana
    state: started

- name: Install Logstash
  apt:
    name: logstash
    update_cache: yes

- name: Start Logstash
  service:
    name: logstash
    state: started
