---
# tasks file for roles/ubuntu/nagios
- name: Install Nagios Core Requisites
  apt:
    name: 
      - build-essential
      - apache2
      - php
      - openssl
      - perl
      - make
      - php-gf
      - libgd-dev
      - libapache2-mod-php
      - libperl-dev
      - libssl-dev
      - daemon
      - wget
      - apache2-utils
      - unzip
    state: latest
    update_cache: yes

- name: Add Group Nagios Core Document
  group:
    name: nagcmd
    state: present

- name: Add user
  user:
     name: nagios
     group: nagcmd
