---
# tasks file for roles/centos/elk
- name: Install Elasticseach Prerequisites
  yum:
    name: java-11-openjdk-devel
    state: present
    update_cache: yes

- name: Install Elasticsearch Repository
  yum_repository:
    name: Elastic_7.X_repo
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    description: Elastic 7.x repo

- name: Add Elasticsearch GPG key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install Elasticsearch
  yum:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Configure  Elasticsearch Network
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.host: localhost'

- name: Configure Elasticsearch Port
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'http.port:'
    line: 'http.port: 9200'

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started

- name: Install Logstash Repository
  yum_repository:
    name: Elastic repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-key-elasticsearch
    enabled: yes
    description: Elastic 7.x packages repo

- name: Install Logstach
  yum:
    name: logstash
    state: present
    update_cache: yes

- name: Configure Logstash Host
  lineinfile:
    destfile: /etc/logstash/logstash.yml
    regexp: 'http.host:'
    line: 'http.host: 127.0.0.1'

- name: Start Logstash
  service:
    name: logstash
    state: started

- name: Install Kibana Repository
  yum_repository:
    name: Kibana 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    description: Kibana-7.x

- name: Install Kibana
  yum:
    name: kibana
    state: present
    update_cache: yes

- name: Configure Kibana host
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.host:'
    line: 'server.host: 0.0.0.0'

- name: Configure Kibana port
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.port:'
    line: 'server.port: 5601'

- name: Start Kibana
  service:
    name: kibana
    state: started
